CREATE TABLE IF NOT EXISTS AVERAGE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(20) NOT NULL,
    EVENT_DATE INTEGER NOT NULL,
    VALUE_SUM DECIMAL(19, 4) NOT NULL,
    COUNT INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS AVERAGE_UIDX ON AVERAGE(EVENT_TYPE, EVENT_DATE);